# .graphclientrc.yml
sources:
  - name: yoki2
    handler:
      graphql:
        endpoint: https://api.studio.thegraph.com/query/64002/yoki2/version/latest
        subgraphError: allow  # Add this line

documents:
  - ./queries/season.graphql