postgres:
  image: postgres:14
  ports:
    - '5432:5432'
  command:
    [
      "postgres",
      "-cshared_preload_libraries=pg_stat_statements"
    ]
  environment:
    POSTGRES_USER: graph-node
    POSTGRES_PASSWORD: let-me-in
    POSTGRES_DB: graph-node
    PGDATA: "/var/lib/postgresql/data"  # Use default path
    POSTGRES_INITDB_ARGS: "--locale=C"
    LC_COLLATE: "C"
    LC_CTYPE: "C"
  volumes:
    - postgres-data:/var/lib/postgresql/data

volumes:
  postgres-data:
    # Force recreation by adding a unique name
    name: postgres_data_c_locale